# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Scripts/ui/assistant.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssistantWindow(QtWidgets.QMainWindow):
    def __init__(self): 
        QtWidgets.QMainWindow.__init__(self)
        self.setupUi()
        self.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self._hide_all() 
    #     QtWidgets.qApp.focusChanged.connect(self.on_focusChanged)

    # @QtCore.pyqtSlot("QWidget*", "QWidget*")
    # def on_focusChanged(self, old, now):

    #     print(f"\nwindow is the active window: {self.isActiveWindow()}")

    def _hide_all(self): 
        self.qr_button.setVisible(False) 
        self.imshow.setVisible(False)
        self.cancel_button.setVisible(False)
        self.calendarWidget.setVisible(False)
        self.label.setVisible(False)
        self.richText.setVisible(False)
        self.insert_button.setVisible(False)

    def setupUi(self):
        self.setObjectName("AssistantWindow")
        self.resize(480, 970)
        self.move(10+860, 10)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -71, 457, 909))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.idle_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idle_label.sizePolicy().hasHeightForWidth())
        self.idle_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.idle_label.setFont(font)
        self.idle_label.setStyleSheet("color:lightgray")
        self.idle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.idle_label.setObjectName("idle_label")
        self.verticalLayout_2.addWidget(self.idle_label)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qr_button = QtWidgets.QPushButton(self.frame)
        self.qr_button.setObjectName("qr_button")
        self.horizontalLayout.addWidget(self.qr_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 150, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imshow = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imshow.sizePolicy().hasHeightForWidth())
        self.imshow.setSizePolicy(sizePolicy)
        self.imshow.setMinimumSize(QtCore.QSize(240, 240))
        self.imshow.setStyleSheet("background:#282828; border: 5px solid gray;")
        self.imshow.setText("")
        self.imshow.setObjectName("imshow")
        self.horizontalLayout_2.addWidget(self.imshow)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_3.addWidget(self.cancel_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_4.addWidget(self.calendarWidget)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("Recommended text:")
        self.verticalLayout_4.addWidget(self.label)
        self.richText = QtWidgets.QTextEdit(self.frame) 
        self.verticalLayout_4.addWidget(self.richText)
        self.insert_button = QtWidgets.QPushButton(self.frame)
        self.insert_button.setText("Insert")
        self.verticalLayout_4.addWidget(self.insert_button)
        self.label1 = QtWidgets.QLabel(self.frame)
        self.label1.setText("Available values:")
        self.label1.setStyleSheet("margin: 20px 0px 0px 0px")
        self.verticalLayout_4.addWidget(self.label1)

        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.verticalLayout_4.addLayout(self.horizontalLayout3)
        
        self.after_breakfast = QtWidgets.QPushButton(self.frame)
        self.after_breakfast.setText("after_breakfast")
        self.horizontalLayout3.addWidget(self.after_breakfast)
        self.before_breakfast = QtWidgets.QPushButton(self.frame)
        self.before_breakfast.setText("before_breakfast")
        self.horizontalLayout3.addWidget(self.before_breakfast)

        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.verticalLayout_4.addLayout(self.horizontalLayout4)

        self.after_lunch = QtWidgets.QPushButton(self.frame)
        self.after_lunch.setText("after_lunch")
        self.horizontalLayout4.addWidget(self.after_lunch)
        self.before_lunch = QtWidgets.QPushButton(self.frame)
        self.before_lunch.setText("before_lunch")
        self.horizontalLayout4.addWidget(self.before_lunch)

        self.horizontalLayout5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout5.setObjectName("horizontalLayout5")
        self.verticalLayout_4.addLayout(self.horizontalLayout5)
        
        self.after_dinner = QtWidgets.QPushButton(self.frame)
        self.after_dinner.setText("after_dinner")
        self.horizontalLayout5.addWidget(self.after_dinner)
        self.before_dinner = QtWidgets.QPushButton(self.frame)
        self.before_dinner.setText("before_dinner")
        self.horizontalLayout5.addWidget(self.before_dinner)

        self.label2 = QtWidgets.QLabel(self.frame)
        self.label2.setText("Insert clock time:")
        self.label2.setStyleSheet("margin: 20px 0px 0px 0px")
        self.verticalLayout_4.addWidget(self.label2)

        self.horizontalLayout6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout6.setObjectName("horizontalLayout6")
        self.verticalLayout_4.addLayout(self.horizontalLayout6)

        self.time_textbox = QtWidgets.QLineEdit(self.frame)
        self.time_textbox.setPlaceholderText("0:00")
        self.horizontalLayout6.addWidget(self.time_textbox)

        self.am = QtWidgets.QPushButton(self.frame)
        self.am.setText("AM")
        self.horizontalLayout6.addWidget(self.am)
        self.pm = QtWidgets.QPushButton(self.frame)
        self.pm.setText("PM")
        self.horizontalLayout6.addWidget(self.pm)

        self.after_breakfast.setVisible(False)
        self.after_dinner.setVisible(False)
        self.after_lunch.setVisible(False)
        self.before_breakfast.setVisible(False)
        self.before_dinner.setVisible(False)
        self.before_lunch.setVisible(False)
        self.label1.setVisible(False)
        self.label2.setVisible(False)
        self.time_textbox.setVisible(False)
        self.am.setVisible(False)
        self.pm.setVisible(False)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("AssistantWindow", "Assistant"))
        self.idle_label.setText(_translate("AssistantWindow", "No Suggestion"))
        self.qr_button.setText(_translate("AssistantWindow", "Scan QR / Barcode"))
        self.cancel_button.setText(_translate("AssistantWindow", "Cancel"))
